### ISSUE TITLE
Collapse_dry: Varying density instead of rho0

### ISSUE THREAD

**Issue by BobNuSpace** [OndrejKincl/SmoothedParticles.jl#6]
I was looking at collapse_dry and comparing it to Monaghan's 2005 SPH review paper. 

@inbounds function internal_force!(p::Particle, q::Particle, r::Float64)
	if p.type == FLUID
		ker = m*rDwendland2(h,r)
		p.a += -ker*(p.P/rho0^2 + q.P/rho0^2)*(p.x - q.x)
		p.a += +2*ker*mu/rho0^2*(p.v - q.v)
	end
end

Should the density vary by position instead of rho0?

@inbounds function internal_force!(p::Particle, q::Particle, r::Float64)
	if p.type == FLUID
		ker = m*rDwendland2(h,r)
		p.a += -ker*(p.P/p.rho^2 + q.P/q.rho^2)*(p.x - q.x)
		p.a += +2*ker*mu/rho0^2*(p.v - q.v)
	end
end

**Comment by OndrejKincl** [comment]
Yes, you are right. I think ` rho0` also works with different formula for pressure and energy. However, it is better to be consistent with Monaghan so I will change this in the next update. Internal energy should change from
`internal =  0.5*m*c^2*(p.rho - rho0)^2/rho0^2`
to
`internal =  m*c^2*(rho0/p.rho + log(p.rho/rho0) - 1.0)`
Thank you for pointing this out!

**Comment by OndrejKincl** [comment]
In new version, pressure is made consistent with Monaghan in example _collapse_dry_ and _cavity_flow_. I also added comparison with referential solutions. I will revise other examples in future.
If you would like to give us some additional feedback we would highly appreciate it.
